[tools]
actionlint = "1.7.8"
age = "1.2.1"
chezmoi = "2.67.0"
cosign = "3.0.2"
go = "1.25.4"
golangci-lint = "2.6.1"
"npm:markdownlint-cli" = "0.45.0"
pnpm = "10.22.0"
ruby = "3.4.7"
shellcheck = "0.11.0"
task = "3.45.4"

[settings]
experimental = true
