[tools]
"aqua:mrtazz/checkmake" = "0.2.2"
cosign = "3.0.2"
go = "1.25.4"
golangci-lint = "2.6.1"
"npm:markdownlint-cli" = "0.45.0"
pnpm = "10.21.0"
ruby = "3.4.7"
shellcheck = "0.11.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
